### ISSUE TITLE
When using a tailwind utility class for the first time you have to restart `npm start`

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-react-checkout#140]
I just noticed, while using the develop branch (maybe 1,5 week old). That certain tailwind utility classes werent applying any styling while using `npm start` and getting page reloads. After some debugging it appeared to be that classes which were never used before were the main culprit.

So say I wanted to add some `p-24` padding for the first time to a component
```jsx
<div className="p-24" />
```
The changes would be picked up by `npm start` process, page reloads, but to my suprise the div doesnt have any padding.

Now when u stop and restart again `npm start`, suddenly the `div` has padding! This happens for classes and extends specified in `reactapp/src/tailwind.config.js` too!

I feel like this is a recent bug, but it is possible I just never noticed it. Is it a limitation of the tailwind implementation somehow?

**Comment by peterschriever** [comment]
Closing since I was told this is due to our project configuration changes

**Comment by progammer-rkt** [comment]
@peterschriever Nope, I dont think this is specific to your project. It is a known issue at least to me. 

This is happening because, when we do `npm start` we will be building the tailwind in dev mode and thus the create the style sheet. This style sheet we are included in the `index.html` file which is what is used in the `npm start`. So the style file created during this process will only contain the used styles in the app. Due to this, if you add any new tailwindcss class, it wont be applied. To reapply it, you need to build the style again and then refresh page or as you stated just kill the `npm start` and then restart again.

What we need to do here is, we need to monitor tailwindcss classes changes along with react in start mode. I tried to do it a  long time before, but could not succeeded. Tbh, I am not a tailwindcss veteran. 

Is this "monitoring" really needed? I know it is good to have. But, we can live without it too??

**Comment by peterschriever** [comment]
Hmm perhaps @jesse-deboer can share his knowledge on this. I believe he had a good idea on how to set up tailwind in a way that solves this problem too

**Comment by rajeev-k-tomy** [comment]
In the next major version release `2.x`, we will be using TailwindCSS in JIT mode which will allow us to avoid this issue.

Maybe we should do the same in the `1.x` version too.
