### ISSUE TITLE
Expected type CustomerAddressRegionInput to be an object at value.region

### ISSUE THREAD

**Issue by gfobe** [hyva-themes/magento2-react-checkout#222]
I use the [demo Hyvä of Elgentos](https://hyva-demo.elgentos.io/). I'm a logged in customer having an address in customer account having 2 street lines (see error message). I try to change my selected address in Hyvä Checkout. When I input datawith a country don't having and region (see data in picture) and save, I got error message `Variable "$customerAddress" got invalid value [...]  Expected type CustomerAddressRegionInput to be an object at value.region.` in both `sendRequest.js:61` and `actions.js:166`. But the address is saved successfully.

![Variable $customerAddress got invalid value](https://user-images.githubusercontent.com/1615283/141455789-c01be3b2-2cf1-496d-be09-3fdd85fca674.png)

I would expect no error message, because there is no region to check.

**Comment by rajeev-k-tomy** [comment]
Thank you for reporting this issue. This is an issue recently encountered on my side too.

The reason is when you edit an address, there can be three mutations possible upon saving.

1. Save shipping address.
2. Save billing address (if shipping address === billing address)
3. Update customer address based on your edit.

Here the mutation number 3 fails currently if there is no region. The first two mutations will work without any problems. Hence you won't see any problem with the checkout page. 

The customer address update mutation must be corrected.

**Comment by rajeev-k-tomy** [comment]
This issue no longer exists now as we completely removed customer address update from the checkout page.
