### ISSUE TITLE
Product details block content is invisible

### ISSUE THREAD

**Issue by m1sha87** [hyva-themes/magento2-react-checkout#288]
I installed clear Magento CE 2.4.4,  Hyva theme 1.1.14, and Hyva React Checkout 1.0.8.
On the checkout page there are some problems with Product details block:
- Not correct margin
![image](https://user-images.githubusercontent.com/16059045/171838959-1ae10c14-4fcd-457a-a9f1-b327e5e30e55.png)
- Invisible content
![image](https://user-images.githubusercontent.com/16059045/171839090-a20d211b-2928-4124-8d6c-6f8a68c22a3d.png)
- slick doesn't work
![image](https://user-images.githubusercontent.com/16059045/171839153-bd05f1e8-c6cf-4a7f-a677-253f2d886f04.png)

In mobile view it shows properly:
![image](https://user-images.githubusercontent.com/16059045/171839291-9cb0b7d9-14a8-4f18-86ac-cb582951e109.png)

When I run Hyva React Checkout as a separate app, there are no such problems:
![image](https://user-images.githubusercontent.com/16059045/171839653-4d1250a5-ed43-4e1e-8d35-1e86e0733878.png)

**Comment by wigman** [comment]
You are missing the tailwind css classes in your Hyvä Theme. Make sure you add the react checkout to the purge paths so that the missing classes are being generated.
https://docs.hyva.io/hyva-themes/working-with-tailwindcss/tailwind-purging-settings.html

PS. in Hyvä 1.1.15 you don't need to manually edit the purge settings with the latest version of the React Checkout (https://docs.hyva.io/hyva-themes/compatibility-modules/tailwind-config-merging.html), as it was implemented here: https://github.com/hyva-themes/magento2-react-checkout/pull/293
