### ISSUE TITLE
Having issue with shopping after installation of react checkout

### ISSUE THREAD

**Issue by Faniiiiiii** [hyva-themes/magento2-react-checkout#290]
![CaptureERROE](https://user-images.githubusercontent.com/105783316/171848354-9718622e-7ca4-4f72-b289-9f175a60db22.PNG)

I have an issue with my shopping cart

**Comment by rajeev-k-tomy** [comment]
This is cart page where you are facing these issues. React checkout has nothing to do with the cart page. It works only in the checkout page.

So the issue may be happening due to the reason @wigman pointed above. 

Closing this issue for the time being. If you still see this is an issue with react-checkout, then feel free to reopen it/
