### ISSUE TITLE
Error message css class issue bg-red-400 -> bg-red-500

### ISSUE THREAD

**Issue by ilker-capli** [hyva-themes/magento2-react-checkout#306]
After fresh installation go to checkout and try to apply invalid coupon code.

error message seems with missing bg-red-400 class.

**Comment by wigman** [comment]
The build includes environment specific information, it would probably be best to remove the build commit and just push the CSS changes and then we publish a new build file once we tag a new version later on.

Otherwise, please create a new build on a vanilla clone of this repository :)

![image](https://user-images.githubusercontent.com/4800926/194868415-7de9027e-ea39-40ec-be01-a34f05d9749a.png)
